# Generated by Django 4.2 on 2023-04-26 12:05

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BasicAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('township', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('zip_code', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='BasicBranch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='BasicPhoneDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_type', models.CharField(max_length=100)),
                ('phone_no', models.CharField(max_length=100)),
                ('country_code', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('full_name', models.CharField(max_length=150)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=150)),
                ('profile_pic', models.CharField(default='', max_length=550)),
                ('status', models.CharField(default='active', max_length=150)),
                ('designation', models.CharField(default='', max_length=150)),
                ('department', models.CharField(default='', max_length=150)),
                ('gender', models.CharField(max_length=10)),
                ('created_time', models.DateTimeField(default=datetime.datetime(2023, 4, 26, 17, 35, 43, 479311))),
                ('is_active', models.BooleanField(default=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('access_level', models.CharField(max_length=150)),
                ('emp_id', models.CharField(max_length=150)),
                ('admin_id', models.CharField(max_length=150)),
                ('access_given_by', models.CharField(max_length=150)),
                ('user_role', models.CharField(max_length=150)),
                ('last_modified_time', models.DateTimeField(default=datetime.datetime(2023, 4, 26, 17, 35, 43, 480309))),
                ('address', models.ManyToManyField(to='users.basicaddress')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.basicbranch')),
                ('phone_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.basicphonedetails')),
            ],
            options={
                'db_table': 'scm_users',
            },
        ),
    ]
